# Generated by Django 4.0.4 on 2022-07-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0002_producto_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristica',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Caracteristica'),
        ),
    ]
