# Generated by Django 4.0.4 on 2022-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0003_producto_caracteristica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristica',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Caracteristica'),
        ),
    ]
