# Generated by Django 4.0.4 on 2022-06-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Categorias')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre Categorias')),
            ],
        ),
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idPlato', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id Plato')),
                ('precio', models.CharField(max_length=10, verbose_name='Precio')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre')),
                ('caracteristica', models.CharField(blank=True, max_length=20, null=True, verbose_name='Caracteristica')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Polls.categoria')),
            ],
        ),
    ]
