# Generated by Django 4.0.4 on 2022-06-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='idPlato',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Id Plato'),
        ),
        migrations.AlterField(
            model_name='comida',
            name='precio',
            field=models.CharField(max_length=10, verbose_name='Precio'),
        ),
    ]
